// Generated by Wrangler for Pages Functions
export interface Env {
  ACA_KV: KVNamespace;
  DB: D1Database;
  IMAGES: R2Bucket;
  ENVIRONMENT: string;
  JWT_SECRET?: string;
  ADMIN_EMAIL?: string;
  CORS_ORIGIN?: string;
  RESEND_API_KEY?: string;
  FROM_EMAIL?: string;
  FRONTEND_URL?: string;
  R2_PUBLIC_URL?: string;
}

// Pages Function context type
export interface PagesFunction<Env = {}> {
  (context: {
    request: Request;
    env: Env;
    params: Record<string, string>;
    data: Record<string, any>;
    next: (input?: RequestInfo | Request, init?: RequestInit) => Promise<Response>;
    waitUntil: (promise: Promise<any>) => void;
  }): Promise<Response> | Response;
}

// Request handler types for different HTTP methods
export interface PagesRequestHandler<Env = {}> extends PagesFunction<Env> { }

declare const onRequestGet: PagesRequestHandler<Env>;
declare const onRequestPost: PagesRequestHandler<Env>;
declare const onRequestPut: PagesRequestHandler<Env>;
declare const onRequestPatch: PagesRequestHandler<Env>;
declare const onRequestDelete: PagesRequestHandler<Env>;
declare const onRequest: PagesRequestHandler<Env>;