#!/bin/bash

echo "=================================================="
echo "MIGRACIÓN DE IMÁGENES R2"
echo "=================================================="

echo ""
echo "Para migrar imágenes entre cuentas de Cloudflare R2 necesitas:"
echo ""
echo "1. Las credenciales de R2 de AMBAS cuentas"
echo "2. Rclone instalado"
echo ""
echo "OPCIONES DE MIGRACIÓN:"
echo ""
echo "A) Usando Rclone (RECOMENDADO para muchas imágenes)"
echo "B) Usando Wrangler (manual, mejor para pocas imágenes)"
echo "C) Subir imágenes nuevas después del deploy"
echo ""

read -p "¿Qué opción prefieres? (A/B/C): " OPCION

if [ "$OPCION" = "A" ] || [ "$OPCION" = "a" ]; then
    echo ""
    echo "=================================================="
    echo "OPCIÓN A: MIGRACIÓN CON RCLONE"
    echo "=================================================="
    echo ""
    echo "1. Instala Rclone si no lo tienes:"
    echo "   brew install rclone"
    echo ""
    echo "2. Obtén las credenciales de R2 de AMBAS cuentas:"
    echo ""
    echo "   CUENTA ANTIGUA (juecart@gmail.com):"
    echo "   - Ve a: https://dash.cloudflare.com/172194a6569df504cbb8a638a94d3d2c/r2/overview"
    echo "   - Manage R2 API Tokens > Create API Token"
    echo "   - Guarda: Access Key ID y Secret Access Key"
    echo ""
    echo "   CUENTA NUEVA (webmaster@acachile.com):"
    echo "   - Ve a: https://dash.cloudflare.com/876bb78a66fe6e1932038334d6f44117/r2/overview"
    echo "   - Manage R2 API Tokens > Create API Token"
    echo "   - Guarda: Access Key ID y Secret Access Key"
    echo ""
    echo "3. Configura Rclone:"
    echo "   rclone config"
    echo ""
    echo "   Para cada cuenta, configura:"
    echo "   - Type: s3"
    echo "   - Provider: Cloudflare"
    echo "   - Access Key: <tu access key>"
    echo "   - Secret Key: <tu secret key>"
    echo "   - Endpoint: https://<ACCOUNT_ID>.r2.cloudflarestorage.com"
    echo ""
    echo "4. Migra las imágenes:"
    echo "   rclone sync old-account:aca-chile-images new-account:aca-chile-images -P"
    echo ""
    
elif [ "$OPCION" = "B" ] || [ "$OPCION" = "b" ]; then
    echo ""
    echo "=================================================="
    echo "OPCIÓN B: MIGRACIÓN MANUAL CON WRANGLER"
    echo "=================================================="
    echo ""
    echo "Esta opción requiere hacer login en ambas cuentas alternadamente."
    echo ""
    echo "1. Login en cuenta ANTIGUA:"
    echo "   wrangler logout"
    echo "   wrangler login"
    echo "   # Selecciona: juecart@gmail.com"
    echo ""
    echo "2. Listar imágenes:"
    echo "   wrangler r2 object list aca-chile-images"
    echo ""
    echo "3. Descargar cada imagen:"
    echo "   mkdir -p temp-images"
    echo "   wrangler r2 object get aca-chile-images/<ruta> --file=temp-images/<nombre>"
    echo ""
    echo "4. Login en cuenta NUEVA:"
    echo "   wrangler logout"
    echo "   wrangler login"
    echo "   # Selecciona: webmaster@acachile.com"
    echo ""
    echo "5. Subir cada imagen:"
    echo "   wrangler r2 object put aca-chile-images/<ruta> --file=temp-images/<nombre>"
    echo ""
    
elif [ "$OPCION" = "C" ] || [ "$OPCION" = "c" ]; then
    echo ""
    echo "=================================================="
    echo "OPCIÓN C: SUBIR IMÁGENES NUEVAS"
    echo "=================================================="
    echo ""
    echo "Si prefieres empezar de cero o las imágenes no son críticas:"
    echo ""
    echo "1. Deploy la aplicación primero"
    echo "2. Usa la interfaz web para subir nuevas imágenes"
    echo "3. O usa la API para subir imágenes:"
    echo "   wrangler r2 object put aca-chile-images/eventos/<nombre> --file=<archivo>"
    echo ""
    
else
    echo "Opción no válida"
    exit 1
fi

echo ""
echo "=================================================="
echo "INFORMACIÓN ÚTIL"
echo "=================================================="
echo ""
echo "Cuenta antigua:"
echo "  Email: juecart@gmail.com"
echo "  Account ID: 172194a6569df504cbb8a638a94d3d2c"
echo "  Bucket: aca-chile-images"
echo ""
echo "Cuenta nueva:"
echo "  Email: webmaster@acachile.com"
echo "  Account ID: 876bb78a66fe6e1932038334d6f44117"
echo "  Bucket: aca-chile-images"
echo ""
