export { HomePage } from './HomePage';
export { AboutPage } from './AboutPage';
export { JoinPage } from './JoinPage';
export { EventsPage } from './EventsPage';
export { default as EventDetailPage } from './EventDetailPage';
export { CreateEventPage } from './CreateEventPage';
export { MyEventsPage } from './MyEventsPage';
export { AuthPage } from './AuthPage';
export { default as ForgotPasswordPage } from './ForgotPasswordPage';
export { default as ResetPasswordPage } from './ResetPasswordPage';
export { BlogPage, PostDetailPage } from './BlogPage';
export { ContactPage } from './ContactPage';
export { NotFoundPage } from './NotFoundPage';
export { default as AdminPanelPage } from './AdminPanelPage';

// Nuevas páginas
export { default as NewsPage } from './NewsPage';
export { default as NewsDetailPage } from './NewsDetailPage';
export { default as SearchResultsPage } from './SearchResultsPage';
export { default as AdminDashboard } from './AdminDashboard';
export { default as AdminUsers } from './AdminUsers';
export { default as AdminSocios } from './AdminSocios';
export { default as AdminCuotas } from './AdminCuotas';
export { default as AdminSettings } from './AdminSettings';
export { default as AdminMonitoring } from './AdminMonitoring';
export { default as PanelAdminDashboard } from './PanelAdminDashboard';
export { default as AdminContent } from './AdminContent';
export { default as AdminNews } from './AdminNews';
export { ProfilePage } from './ProfilePage';
export { default as PerfilSocio } from './PerfilSocio';