# Configuraci贸n principal del Worker ACA Chile
name = "acachile-api"
main = "src/index.ts"
compatibility_date = "2024-10-14"

# Variables de entorno para desarrollo
[vars]
ENVIRONMENT = "development"

# Configuraci贸n de KV para almacenamiento
[[kv_namespaces]]
binding = "ACA_KV"
id = "b080082921d447e6995c8085f1033286"
preview_id = "deda506587a1476a96578cb545f0128e"

# Entorno de producci贸n
[env.production]
name = "acachile-api-production"
vars = { ENVIRONMENT = "production" }

# KV para producci贸n
[[env.production.kv_namespaces]]
binding = "ACA_KV"
id = "60fff9f10819406cad241e326950f056"

# Entorno de staging
[env.staging]
name = "acachile-api-staging"
vars = { ENVIRONMENT = "staging" }

[[env.staging.kv_namespaces]]
binding = "ACA_KV"
id = "b080082921d447e6995c8085f1033286"